[theme]
# Configuraci贸n de tema oscuro forzado para Streamlit Cloud
base = "dark"
primaryColor = "#dc2626"  # Rojo Col贸n
backgroundColor = "#0e1117"  # Fondo oscuro
secondaryBackgroundColor = "#262730"  # Fondo secundario
textColor = "#fafafa"  # Texto claro

[server]
# Configuraci贸n del servidor
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Configuraci贸n del navegador
gatherUsageStats = false
